// apps/react-app/src/components/ErrorToast.tsx
import styles from './ErrorToast.module.css';

interface ErrorToastProps {
  message: string;
  actionLabel?: string;
  onAction?: () => void;
  onDismiss?: () => void;
}

export function ErrorToast({ message, actionLabel, onAction, onDismiss }: ErrorToastProps) {
  return (
    <div className={styles.toast} role="alert">
      <span className={styles.message}>{message}</span>
      <div className={styles.actions}>
        {actionLabel ? (
          <button type="button" onClick={onAction}>
            {actionLabel}
          </button>
        ) : null}
        {onDismiss ? (
          <button type="button" className="secondary" onClick={onDismiss} aria-label="Dismiss error">
            ✕
          </button>
        ) : null}
      </div>
    </div>
  );
}

// apps/vue-app/src/components/ErrorToast.vue
<template>
  <div class="error-toast" role="alert">
    <span>{{ message }}</span>
    <div class="error-toast__actions">
      <button v-if="actionLabel" type="button" @click="$emit('action')">{{ actionLabel }}</button>
      <button v-if="dismissible" type="button" class="secondary" @click="$emit('dismiss')" aria-label="Dismiss error">
        ✕
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  message: string;
  actionLabel?: string;
  dismissible?: boolean;
}

withDefaults(defineProps<Props>(), {
  dismissible: true
});

defineEmits<{
  (e: 'action'): void;
  (e: 'dismiss'): void;
}>();
</script>

<style scoped>
.error-toast {
  display: flex;
  justify-content: space-between;
  gap: 16px;
  padding: 12px 16px;
  border-radius: var(--radius-md);
  background: rgba(255, 85, 85, 0.15);
  border: 1px solid rgba(255, 85, 85, 0.35);
  align-items: center;
}

.error-toast__actions {
  display: flex;
  gap: 8px;
}
</style>
